/*
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Project: Cornos
# File: Test
# Created by constantin at 21:26, Mär 17 2021
PLEASE READ THE COPYRIGHT NOTICE IN THE PROJECT ROOT, IF EXISTENT
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
*/
package me.zeroX150.cornos.features.module.impl.misc;

import me.zeroX150.cornos.Cornos;
import me.zeroX150.cornos.features.module.Module;
import me.zeroX150.cornos.features.module.ModuleType;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.DoubleTag;
import net.minecraft.nbt.StringTag;
import net.minecraft.network.packet.c2s.play.CreativeInventoryActionC2SPacket;
import net.minecraft.text.Text;
import net.minecraft.util.Hand;
import net.minecraft.util.hit.BlockHitResult;
import net.minecraft.util.math.Direction;
import net.minecraft.util.math.Vec3d;

import java.util.Random;

public class Test extends Module {
    int timeout = 0;

    public Test() {
        super("TestModule", "j", ModuleType.HIDDEN);
    }

    @Override
    public void onEnable() {
        ItemStack itemStack = new ItemStack(Items.BAT_SPAWN_EGG);
        itemStack.setCustomName(Text.of("§r§cOuch. §4Generated by §lCornos"));
        CompoundTag compoundTag = itemStack.getOrCreateSubTag("EntityTag");
        compoundTag.put("id", StringTag.of("minecraft:fireball"));
        compoundTag.put("ExplosionPower", DoubleTag.of(15));
        CreativeInventoryActionC2SPacket p = new CreativeInventoryActionC2SPacket(36, itemStack);
        Cornos.minecraft.getNetworkHandler().sendPacket(p);
        Random r = new Random();
        for (int ii = 0; ii < 500; ii++) {
            double x = (r.nextDouble() - .5) * 15;
            double z = (r.nextDouble() - .5) * 15;
            double y = (r.nextDouble() - .5) * 15;
            BlockHitResult bhr = new BlockHitResult(Vec3d.ZERO, Direction.DOWN, Cornos.minecraft.player.getBlockPos().add(x, y, z), false);
            Cornos.minecraft.interactionManager.interactBlock(Cornos.minecraft.player, Cornos.minecraft.world, Hand.MAIN_HAND, bhr);
        }
        setEnabled(false);
    }

    @Override
    public void onExecute() {
        int i = 10;
        timeout++;
        if (timeout > 1) timeout = 0;
        //else return;

    }
}
