/*
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Project: Cornos
# File: Fireball 
# Created by saturn5Vfive
PLEASE READ THE COPYRIGHT NOTICE IN THE PROJECT ROOT, IF EXISTENT
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
*/
package me.constantindev.ccl.command;

import me.constantindev.ccl.Cornos;
import me.constantindev.ccl.etc.base.Command;
import net.minecraft.item.ItemStack;
import me.constantindev.ccl.etc.helper.STL;
import net.minecraft.util.Identifier;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.StringNbtReader;
import net.minecraft.network.packet.c2s.play.CreativeInventoryActionC2SPacket;
import net.minecraft.item.Item;
import net.minecraft.item.Items;
import net.minecraft.nbt.*;

public class Fireball extends Command {
    public Fireball() {
        super("Fireball", "big or smol fireballs", new String[]{"fireball", "fb"});
    }

    @Override
    public void onExecute(String[] args) {
        if (args.length != 1) {
            STL.notifyUser("Provide a number");
            return;
        }
        ItemStack fb = new ItemStack(Items.BLAZE_SPAWN_EGG, 1);
        try{
            fb.setTag(createNBT(Integer.parseInt(args[0])));
        }catch(Exception e){
            STL.notifyUser("Provide a number");
        }
        Cornos.minecraft.getNetworkHandler().sendPacket(new CreativeInventoryActionC2SPacket(36 + Cornos.minecraft.player.inventory.selectedSlot, fb)); //better doin this as the item is server side to begin with
        super.onExecute(args);
    }

    private CompoundTag createNBT(Integer fireballpower)
	{
		try
		{
			return StringNbtReader.parse("{display:{Name:'[{\"text\":\"Fireball \",\"color\":\"red\",\"bold\":true,\"italic\":false},{\"text\":\" of power \",\"color\":\"red\",\"bold\":false,\"italic\":false},{\"text\":\""+ fireballpower +"\",\"color\":\"red\",\"italic\":false},{\"text\":\" Generated by Cornos\",\"color\":\"dark_red\",\"bold\":true,\"italic\":false}]'},EntityTag:{id:\"minecraft:fireball\",ExplosionPower:"+ fireballpower +",power:[0.0,-1.0,0.0]}}");
			
		}catch(Exception e) //w
		{
            return null;
		}
	}
}
